// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: xrpc.proto
#ifndef GRPC_xrpc_2eproto__INCLUDED
#define GRPC_xrpc_2eproto__INCLUDED

#include "xrpc.pb.h"

#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/method_handler_impl.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace grpc {
class CompletionQueue;
class Channel;
class ServerCompletionQueue;
class ServerContext;
}  // namespace grpc

namespace top {

class xrpc_service final {
 public:
  static constexpr char const* service_full_name() {
    return "top.xrpc_service";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status call(::grpc::ClientContext* context, const ::top::xrpc_request& request, ::top::xrpc_reply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::top::xrpc_reply>> Asynccall(::grpc::ClientContext* context, const ::top::xrpc_request& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::top::xrpc_reply>>(AsynccallRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::top::xrpc_reply>> PrepareAsynccall(::grpc::ClientContext* context, const ::top::xrpc_request& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::top::xrpc_reply>>(PrepareAsynccallRaw(context, request, cq));
    }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::top::xrpc_reply>* AsynccallRaw(::grpc::ClientContext* context, const ::top::xrpc_request& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::top::xrpc_reply>* PrepareAsynccallRaw(::grpc::ClientContext* context, const ::top::xrpc_request& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status call(::grpc::ClientContext* context, const ::top::xrpc_request& request, ::top::xrpc_reply* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::top::xrpc_reply>> Asynccall(::grpc::ClientContext* context, const ::top::xrpc_request& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::top::xrpc_reply>>(AsynccallRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::top::xrpc_reply>> PrepareAsynccall(::grpc::ClientContext* context, const ::top::xrpc_request& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::top::xrpc_reply>>(PrepareAsynccallRaw(context, request, cq));
    }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    ::grpc::ClientAsyncResponseReader< ::top::xrpc_reply>* AsynccallRaw(::grpc::ClientContext* context, const ::top::xrpc_request& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::top::xrpc_reply>* PrepareAsynccallRaw(::grpc::ClientContext* context, const ::top::xrpc_request& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_call_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status call(::grpc::ServerContext* context, const ::top::xrpc_request* request, ::top::xrpc_reply* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_call : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_call() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_call() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status call(::grpc::ServerContext* context, const ::top::xrpc_request* request, ::top::xrpc_reply* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void Requestcall(::grpc::ServerContext* context, ::top::xrpc_request* request, ::grpc::ServerAsyncResponseWriter< ::top::xrpc_reply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_call<Service > AsyncService;
  template <class BaseClass>
  class WithGenericMethod_call : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_call() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_call() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status call(::grpc::ServerContext* context, const ::top::xrpc_request* request, ::top::xrpc_reply* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_call : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithRawMethod_call() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_call() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status call(::grpc::ServerContext* context, const ::top::xrpc_request* request, ::top::xrpc_reply* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void Requestcall(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_call : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithStreamedUnaryMethod_call() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler< ::top::xrpc_request, ::top::xrpc_reply>(std::bind(&WithStreamedUnaryMethod_call<BaseClass>::Streamedcall, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithStreamedUnaryMethod_call() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status call(::grpc::ServerContext* context, const ::top::xrpc_request* request, ::top::xrpc_reply* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status Streamedcall(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::top::xrpc_request,::top::xrpc_reply>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_call<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_call<Service > StreamedService;
};

}  // namespace top


#endif  // GRPC_xrpc_2eproto__INCLUDED
